[template]
directory = "lua_template"

[watch]
paths = [
    "lua_template/**/*.lua",
    "lua_template/**/*.toml",
    "lua_template/**/*.yml",
    "lua_template/**/*.yaml",
    "lua_template/**/*.json",
    "lua_template/**/*.jinja",
]
